import { test, expect } from "@playwright/test";
import { initialTree, applyCommand, withAnswer } from "../../src/model";
import { normalizeMathDelimiters } from "../../src/math-markdown";

test("formula clipboard uses Markdown delimiters for native, menu, partial and whole reply copying", async ({ page, request, context }) => {
  const root = initialTree();
  const project = applyCommand(root, { type: "create", parentId: root.rootId, kind: "project", title: "公式复制测试" });
  const chat = applyCommand(project.data, { type: "create", parentId: project.selectedId, kind: "chat", title: "公式示例", question: "如何复制公式？" });
  const source = '行内公式 \\(E=mc^2\\) 与文字。\n\n\\[\\frac{a}{b}=c\\]\n\n结尾文字。代码 `\\(literal\\)` 不应转换。';
  const data = withAnswer(chat.data, chat.selectedId, source, "model");
  const old = await (await request.get("/api/tree")).json();
  expect((await request.post("/api/restore", { data: { data, revision: old.data.revision } })).ok()).toBe(true);
  await context.grantPermissions(["clipboard-read", "clipboard-write"]);
  await page.goto("/");
  await page.getByRole("tree").getByRole("button", { name: "公式复制测试", exact: true }).click();
  await page.getByRole("tree").getByRole("button", { name: "公式示例", exact: true }).click();
  const markdown = page.locator(".answer-section .markdown");
  await expect(markdown.locator(".katex")).toHaveCount(2);
  const inline = markdown.locator(".katex-html").first();
  const display = markdown.locator(".katex-display .katex-html");
  const select = async (locator: typeof inline) => locator.evaluate(element => {
    const range = document.createRange();
    range.selectNodeContents(element);
    const selection = getSelection()!;
    selection.removeAllRanges();
    selection.addRange(range);
  });
  const clipboard = () => page.evaluate(() => navigator.clipboard.readText());
  await select(inline);
  await page.keyboard.press("Control+c");
  await expect.poll(clipboard).toBe("$E=mc^2$");
  await select(display);
  await page.keyboard.press("Control+c");
  await expect.poll(clipboard).toBe("$$\n\\frac{a}{b}=c\n$$");
  await select(display.locator(".mord").last());
  await page.keyboard.press("Control+c");
  await expect.poll(clipboard).toBe("$$\n\\frac{a}{b}=c\n$$");
  await select(inline);
  await inline.click({ button: "right" });
  await page.getByRole("menuitem", { name: "复制", exact: true }).click();
  await expect.poll(clipboard).toBe("$E=mc^2$");
  await select(markdown);
  await page.keyboard.press("Control+c");
  const mixed = await clipboard();
  expect(mixed).toContain("行内公式 $E=mc^2$ 与文字。");
  expect(mixed).toContain("$$\n\\frac{a}{b}=c\n$$");
  expect(mixed.match(/E=mc\^2/g)).toHaveLength(1);
  expect(mixed).toContain("结尾文字。");
  await page.getByRole("button", { name: "复制回复", exact: true }).click();
  await expect.poll(clipboard).toBe(normalizeMathDelimiters(source));
  expect(await clipboard()).toContain('`\\(literal\\)`');
});
